#!/bin/bash
# Author: Sebastian Opiyo
# Date Created: Jun 25, 2020
# Date Modified:
# Description: A ping script for automating ping

hosts="./ip_address"
for host in $(cat $hosts)
	do
		ping -c1 $host
		if [$? -eq 0]
		then 
			echo OK
		else
			echo NOT Ok
		fi
	done

